function c = sprott_catalog(name)
%SPROTT_CATALOG The 62 systems of Sprott (2003) Appendix A.
%
%   c = nonantest.sprott_catalog()       all systems, as a struct array
%   c = nonantest.sprott_catalog(name)   one system by name
%
%   Fields
%     name        short identifier
%     pretty      the name as printed in the appendix
%     section     appendix section, e.g. "A.5.1"
%     category    "noninvertible_map" | "dissipative_map" | "conservative_map"
%                 | "driven_flow" | "autonomous_flow" | "conservative_flow"
%     kind        "map" | "flow"
%     f           map:  v -> v_next.   flow: (t, v) -> dv/dt.
%     x0          initial condition, column vector
%     lambda      largest Lyapunov exponent, NATS per iteration or per unit
%                 time. Sprott states explicitly that all exponents in the
%                 appendix are base-e.
%     tier        "exact" if lambda is a closed form, "numerical" otherwise
%     obs         index of the state variable used as the scalar observable
%     dt          integration step (flows only)
%     usable      false if the system cannot be used as a benchmark, with
%                 the reason in c.note
%
%   PROVENANCE. Sprott, J. C. (2003), Chaos and Time-Series Analysis, Oxford
%   University Press, Appendix A. The appendix header states: "All Lyapunov
%   exponents are base-e and were calculated using the methods in Chapter 5"
%   (trajectory separation with periodic renormalisation), and "Most of the
%   results are original calculations, and all have been independently
%   verified."
%
%   Systems whose lambda is a closed form are marked tier "exact" and can be
%   asserted tightly; the rest are order-of-magnitude checks. The appendix
%   reproduces the exact cases it contains, e.g. the logistic entry reads
%   0.693147181 against ln 2 = 0.6931471806.
%
%   Conservative systems carry lambda = +x, 0, -x by symplectic symmetry;
%   only the largest is stored. Their exponents are small (0.006 to 0.16) and
%   are the most demanding cases in the set.

S = {};

% ---------------------------------------------------------------- A.1 maps
S{end+1} = mk("logistic","Logistic map","A.1.1","noninvertible_map", ...
    @(v) 4*v(1)*(1-v(1)), 0.1, log(2), "exact");
S{end+1} = mk("sine_map","Sine map","A.1.2","noninvertible_map", ...
    @(v) sin(pi*v(1)), 0.1, 0.689067, "numerical");
s = mk("tent","Tent map","A.1.3","noninvertible_map", ...
    @(v) 2*min(v(1),1-v(1)), 1/sqrt(2), log(2), "exact");
s.usable = false;
s.note = ["The slope-2 tent map is exactly a binary shift, so in double " ...
          "precision it consumes one mantissa bit per iteration and reaches " ...
          "exactly 0 after ~52 steps: 52 distinct values in 2000 from " ...
          "Sprott's own x0 = 1/sqrt(2). Sprott specifies an irrational x0 " ...
          "for precisely this reason, but EVERY double is a dyadic rational, " ...
          "so no representable initial condition avoids it. Not an " ...
          "implementation fault and not fixable in double precision; it " ...
          "needs exact or extended arithmetic. Sprott flags the issue at " ...
          "his section 2.5.2."];
S{end+1} = s;
S{end+1} = mk("lcg","Linear congruential generator","A.1.4","noninvertible_map", ...
    @(v) mod(7141*v(1)+54773, 259200), 0, log(7141), "exact");
S{end+1} = mk("cubic_map","Cubic map","A.1.5","noninvertible_map", ...
    @(v) 3*v(1)*(1-v(1)^2), 0.1, 1.0986122883, "numerical");
S{end+1} = mk("ricker","Ricker's population model","A.1.6","noninvertible_map", ...
    @(v) 20*v(1)*exp(-v(1)), 0.1, 0.384846, "numerical");
% Sprott gives x0 = 0.1, but 1/0.1 rounds to exactly 10 in binary floating
% point, so mod(.,1) is exactly 0 and the next step divides by zero -- the
% orbit dies on iteration 1. Any x0 whose reciprocal is not a representable
% integer works; 0.31415926... survives indefinitely. An initial-condition
% artefact of binary arithmetic, not a property of the map.
S{end+1} = mk("gauss_map","Gauss map","A.1.7","noninvertible_map", ...
    @(v) mod(1/v(1),1), 0.3141592653589793, 2.373445, "numerical");
S{end+1} = mk("cusp","Cusp map","A.1.8","noninvertible_map", ...
    @(v) 1-2*sqrt(abs(v(1))), 0.5, 0.5, "exact");
s = mk("gauss_white","Gaussian white chaotic map","A.1.9","noninvertible_map", ...
    @(v) sqrt(2)*erfinv(1-2*erf(v(1)/sqrt(2))), 1, log(2), "exact");
s.usable = false;
s.note = ["Transcribed literally from the appendix as " ...
          "A*erfinv(1 - 2*erf(x/A)), this leaves the domain on step 2: once " ...
          "x goes negative, erf(x/A) < 0, so 1 - 2*erf(x/A) > 1 and erfinv " ...
          "returns NaN. Marked unusable rather than guessed at, because the " ...
          "intended form could not be verified from the appendix page alone. " ...
          "Note also that lambda = ln 2 indicates conjugacy to the doubling " ...
          "map, so even a correct transcription would inherit the same " ...
          "mantissa exhaustion that disqualifies the tent map above."];
S{end+1} = s;
S{end+1} = mk("pinchers","Pinchers map","A.1.10","noninvertible_map", ...
    @(v) abs(tanh(2*(v(1)-0.5))), 0, 0.467944, "numerical");
s = mk("spence","Spence map","A.1.11","noninvertible_map", ...
    @(v) abs(log(v(1))), 0.5, Inf, "exact");
s.usable = false;
s.note = ["lambda -> Inf. No finite reference exists, so it cannot be used " ...
          "as a benchmark. Retained so the catalogue is complete and the " ...
          "exclusion is explicit rather than silent."];
S{end+1} = s;
S{end+1} = mk("sine_circle","Sine-circle map","A.1.12","noninvertible_map", ...
    @(v) mod(v(1)+0.5-(2/(2*pi))*sin(2*pi*v(1)),1), 0.1, 0.353863, "numerical");

% ------------------------------------------------------ A.2 dissipative maps
S{end+1} = mk("henon","Henon map","A.2.1","dissipative_map", ...
    @(v) [1-1.4*v(1)^2+0.3*v(2); v(1)], [0;0.9], 0.41922, "numerical");
S{end+1} = mk("lozi","Lozi map","A.2.2","dissipative_map", ...
    @(v) [1-1.7*abs(v(1))+0.5*v(2); v(1)], [-0.1;0.1], 0.47023, "numerical");
S{end+1} = mk("delayed_logistic","Delayed logistic map","A.2.3","dissipative_map", ...
    @(v) [2.27*v(1)*(1-v(2)); v(1)], [0.001;0.001], 0.18312, "numerical");
S{end+1} = mk("tinkerbell","Tinkerbell map","A.2.4","dissipative_map", ...
    @(v) [v(1)^2-v(2)^2+0.9*v(1)-0.6*v(2); 2*v(1)*v(2)+2*v(1)+0.5*v(2)], ...
    [0;0.5], 0.18997, "numerical");
S{end+1} = mk("burgers","Burgers' map","A.2.5","dissipative_map", ...
    @(v) [0.75*v(1)-v(2)^2; 1.75*v(2)+v(1)*v(2)], [-0.1;0.1], 0.12076, "numerical");
S{end+1} = mk("holmes_cubic","Holmes cubic map","A.2.6","dissipative_map", ...
    @(v) [v(2); -0.2*v(1)+2.77*v(2)-v(2)^3], [1.6;0], 0.59458, "numerical");
s = mk("kaplan_yorke","Kaplan-Yorke map","A.2.7","dissipative_map", ...
    @(v) [mod(2*v(1),1); mod(0.2*v(2)+cos(4*pi*v(1)),1)], [1/sqrt(2);-0.4], ...
    log(2), "exact");
s.usable = false;
s.note = ["The x equation is x -> 2x mod 1, the same binary shift as the " ...
          "tent map, so x reaches exactly 0 after ~51 iterations and the " ...
          "attractor collapses. Same root cause, same non-fixability in " ...
          "double precision; Sprott again refers to his section 2.5.2."];
S{end+1} = s;
S{end+1} = mk("dissipative_standard","Dissipative standard map","A.2.8","dissipative_map", ...
    @(v) dissStd(v), [0.1;0.1], 1.46995, "numerical");
S{end+1} = mk("ikeda","Ikeda map","A.2.9","dissipative_map", ...
    @(v) ikeda(v), [0;0], 0.50760, "numerical");
S{end+1} = mk("sinai","Sinai map","A.2.10","dissipative_map", ...
    @(v) [mod(v(1)+v(2)+0.1*cos(2*pi*v(2)),1); mod(v(1)+2*v(2),1)], ...
    [0.5;0.5], 0.95946, "numerical");
S{end+1} = mk("predator_prey","Discrete predator-prey map","A.2.11","dissipative_map", ...
    @(v) [v(1)*exp(3*(1-v(1))-5*v(2)); v(1)*(1-exp(-5*v(2)))], ...
    [0.5;0.5], 0.19664, "numerical");

% ----------------------------------------------------- A.3 conservative maps
S{end+1} = mk("chirikov","Chirikov (standard) map","A.3.1","conservative_map", ...
    @(v) chirikov(v), [0;6], 0.10497, "numerical");
S{end+1} = mk("henon_area","Henon area-preserving quadratic map","A.3.2","conservative_map", ...
    @(v) henonArea(v), [0.6;0.13], 0.00643, "numerical");
S{end+1} = mk("arnold_cat","Arnold's cat map","A.3.3","conservative_map", ...
    @(v) [mod(v(1)+v(2),1); mod(v(1)+2*v(2),1)], [0;1/sqrt(2)], ...
    log((3+sqrt(5))/2), "exact");
S{end+1} = mk("gingerbreadman","Gingerbreadman map","A.3.4","conservative_map", ...
    @(v) [1+abs(v(1))-v(2); v(1)], [0.5;3.7], 0.07339, "numerical");
S{end+1} = mk("chaotic_web","Chaotic web map","A.3.5","conservative_map", ...
    @(v) chaoticWeb(v), [0;3], 0.04847, "numerical");
S{end+1} = mk("lorenz3d_map","Lorenz three-dimensional chaotic map","A.3.6","conservative_map", ...
    @(v) [v(1)*v(2)-v(3); v(1); v(2)], [0.5;0.5;-1], 0.07456, "numerical");

% ------------------------------------------------------ A.4 driven flows
S{end+1} = mkf("damped_pendulum","Damped driven pendulum","A.4.1","driven_flow", ...
    @(t,v) [v(2); -sin(v(1))-0.05*v(2)+0.6*sin(0.7*t)], [0;0], 0.1414, "numerical", 0.02);
S{end+1} = mkf("driven_vdp","Driven van der Pol oscillator","A.4.2","driven_flow", ...
    @(t,v) [v(2); -v(1)+3*(1-v(1)^2)*v(2)+5*sin(1.788*t)], [-1.9;0], 0.1933, "numerical", 0.005);
S{end+1} = mkf("shaw_vdp","Shaw-van der Pol oscillator","A.4.3","driven_flow", ...
    @(t,v) [v(2)+sin(2*t); -v(1)+1*(1-v(1)^2)*v(2)], [1.3;0], 0.1180, "numerical", 0.01);
S{end+1} = mkf("brusselator","Forced Brusselator","A.4.4","driven_flow", ...
    @(t,v) [v(1)^2*v(2)-(1.2+1)*v(1)+0.4+0.05*sin(0.8*t); -v(1)^2*v(2)+1.2*v(1)], ...
    [0.3;2], 0.0140, "numerical", 0.02);
S{end+1} = mkf("ueda","Ueda oscillator","A.4.5","driven_flow", ...
    @(t,v) [v(2); -v(1)^3-0.05*v(2)+7.5*sin(t)], [2.5;0], 0.1034, "numerical", 0.01);
S{end+1} = mkf("duffing_two_well","Duffing's two-well oscillator","A.4.6","driven_flow", ...
    @(t,v) [v(2); -v(1)^3+v(1)-0.25*v(2)+0.4*sin(t)], [0.2;0], 0.1572, "numerical", 0.02);
S{end+1} = mkf("duffing_vdp","Duffing-van der Pol oscillator","A.4.7","driven_flow", ...
    @(t,v) [v(2); 0.2*(1-8*v(1)^2)*v(2)-v(1)^3+0.35*sin(1.02*t)], [0.2;-0.2], 0.0963, "numerical", 0.02);
S{end+1} = mkf("rayleigh_duffing","Rayleigh-Duffing oscillator","A.4.8","driven_flow", ...
    @(t,v) [v(2); 0.2*(1-4*v(2)^2)*v(2)-v(1)^3+0.3*sin(1.1*t)], [0.3;0], 0.0912, "numerical", 0.02);

% -------------------------------------------------- A.5 autonomous flows
S{end+1} = mkf("lorenz","Lorenz attractor","A.5.1","autonomous_flow", ...
    @(t,v) [10*(v(2)-v(1)); -v(1)*v(3)+28*v(1)-v(2); v(1)*v(2)-(8/3)*v(3)], ...
    [0;-0.01;9], 0.9056, "numerical", 0.003);
S{end+1} = mkf("rossler","Rossler attractor","A.5.2","autonomous_flow", ...
    @(t,v) [-v(2)-v(3); v(1)+0.2*v(2); 0.2+v(3)*(v(1)-5.7)], ...
    [-9;0;0], 0.0714, "numerical", 0.01);
S{end+1} = mkf("diffusionless_lorenz","Diffusionless Lorenz attractor","A.5.3","autonomous_flow", ...
    @(t,v) [-v(2)-v(1); -v(1)*v(3); v(1)*v(2)+1], [1;-1;0.01], 0.2101, "numerical", 0.01);
S{end+1} = mkf("complex_butterfly","Complex butterfly","A.5.4","autonomous_flow", ...
    @(t,v) [0.55*(v(2)-v(1)); -v(3)*sign(v(1)); abs(v(1))-1], [0.2;0;0], 0.1690, "numerical", 0.01);
S{end+1} = mkf("chen","Chen's system","A.5.5","autonomous_flow", ...
    @(t,v) [35*(v(2)-v(1)); (28-35)*v(1)-v(1)*v(3)+28*v(2); v(1)*v(2)-3*v(3)], ...
    [-10;0;37], 2.0272, "numerical", 0.001);
S{end+1} = mkf("hadley","Hadley circulation","A.5.6","autonomous_flow", ...
    @(t,v) [-v(2)^2-v(3)^2-0.25*v(1)+0.25*8; v(1)*v(2)-4*v(1)*v(3)-v(2)+1; ...
            4*v(1)*v(2)+v(1)*v(3)-v(3)], [0;0;1.3], 0.1665, "numerical", 0.01);
S{end+1} = mkf("act","ACT attractor","A.5.7","autonomous_flow", ...
    @(t,v) [1.8*(v(1)-v(2)); -4*1.8*v(2)+v(1)*v(3)+0.02*v(1)^3; ...
            -1.5*v(3)+v(1)*v(2)+(-0.07)*v(3)^2], [0.5;0;0], 0.1634, "numerical", 0.01);
S{end+1} = mkf("rabinovich_fabrikant","Rabinovich-Fabrikant attractor","A.5.8","autonomous_flow", ...
    @(t,v) [v(2)*(v(3)-1+v(1)^2)+0.87*v(1); v(1)*(3*v(3)+1-v(1)^2)+0.87*v(2); ...
            -2*v(3)*(1.1+v(1)*v(2))], [-1;0;0.5], 0.1981, "numerical", 0.005);
S{end+1} = mkf("rigid_body","Linear feedback rigid body motion system","A.5.9","autonomous_flow", ...
    @(t,v) [-0.4*v(1)+v(2)+10*v(2)*v(3); -v(1)-0.4*v(2)+5*v(1)*v(3); ...
            0.175*v(3)-5*v(1)*v(2)], [0.6;0;0], 0.1421, "numerical", 0.01);
S{end+1} = mkf("chua","Chua's circuit","A.5.10","autonomous_flow", ...
    @(t,v) chua(v), [0;0;0.6], 0.3271, "numerical", 0.005);
S{end+1} = mkf("moore_spiegel","Moore-Spiegel oscillator","A.5.11","autonomous_flow", ...
    @(t,v) [v(2); v(3); -v(3)-(6-20+20*v(1)^2)*v(2)-6*v(1)], [0.1;0;0], 0.1119, "numerical", 0.005);
S{end+1} = mkf("thomas","Thomas' cyclically symmetric attractor","A.5.12","autonomous_flow", ...
    @(t,v) [-0.18*v(1)+sin(v(2)); -0.18*v(2)+sin(v(3)); -0.18*v(3)+sin(v(1))], ...
    [0.1;0;0], 0.0349, "numerical", 0.05);
S{end+1} = mkf("halvorsen","Halvorsen's cyclically symmetric attractor","A.5.13","autonomous_flow", ...
    @(t,v) [-1.27*v(1)-4*v(2)-4*v(3)-v(2)^2; -1.27*v(2)-4*v(3)-4*v(1)-v(3)^2; ...
            -1.27*v(3)-4*v(1)-4*v(2)-v(1)^2], [-5;0;0], 0.7899, "numerical", 0.005);
% dz/dt takes +U*x*y. The appendix line reads as "-Uxy + V", but that sign
% diverges at every step size tried (1e-3 to 1e-4, diverging later as dt
% shrinks, which is the signature of a genuinely unbounded solution rather
% than an integration artefact). +U*x*y is the standard Burke-Shaw form and
% is bounded here.
S{end+1} = mkf("burke_shaw","Burke-Shaw attractor","A.5.14","autonomous_flow", ...
    @(t,v) [-10*(v(1)+v(2)); -10*v(1)*v(3)-v(2); 10*v(1)*v(2)+13], ...
    [0.6;0;0], 2.2499, "numerical", 0.001);
S{end+1} = mkf("rucklidge","Rucklidge attractor","A.5.15","autonomous_flow", ...
    @(t,v) [-2*v(1)+6.7*v(2)-v(2)*v(3); v(1); -v(3)+v(2)^2], [1;0;4.5], 0.0643, "numerical", 0.01);
S{end+1} = mkf("windmi","WINDMI attractor","A.5.16","autonomous_flow", ...
    @(t,v) [v(2); v(3); -0.7*v(3)-v(2)+2.5-exp(v(1))], [0;0.8;0], 0.0755, "numerical", 0.01);
S{end+1} = mkf("simplest_quadratic","Simplest quadratic chaotic flow","A.5.17","autonomous_flow", ...
    @(t,v) [v(2); v(3); -2.017*v(3)+v(2)^2-v(1)], [-0.9;0;0.5], 0.0551, "numerical", 0.01);
S{end+1} = mkf("simplest_cubic","Simplest cubic chaotic flow","A.5.18","autonomous_flow", ...
    @(t,v) [v(2); v(3); -2.028*v(3)+v(1)*v(2)^2-v(1)], [0;0.96;0], 0.0837, "numerical", 0.01);
S{end+1} = mkf("simplest_piecewise","Simplest piecewise linear chaotic flow","A.5.19","autonomous_flow", ...
    @(t,v) [v(2); v(3); -0.6*v(3)-v(2)+abs(v(1))-1], [0;-0.7;0], 0.0362, "numerical", 0.02);
S{end+1} = mkf("double_scroll","Double scroll","A.5.20","autonomous_flow", ...
    @(t,v) [v(2); v(3); -0.8*(v(3)+v(2)+v(1)-sign(v(1)))], [0.01;0.01;0], 0.0497, "numerical", 0.02);

% ------------------------------------------------- A.6 conservative flows
S{end+1} = mkf("driven_pendulum","Driven pendulum","A.6.1","conservative_flow", ...
    @(t,v) [v(2); -sin(v(1))+1.0*sin(0.5*t)], [0;0], 0.1633, "numerical", 0.02);
S{end+1} = mkf("simplest_driven","Simplest driven chaotic flow","A.6.2","conservative_flow", ...
    @(t,v) [v(2); -v(1)^3+sin(1.88*t)], [0;0], 0.0971, "numerical", 0.02);
S{end+1} = mkf("nose_hoover","Nose-Hoover oscillator","A.6.3","conservative_flow", ...
    @(t,v) [v(2); -v(1)+v(2)*v(3); 1-v(2)^2], [0;5;0], 0.0138, "numerical", 0.02);
S{end+1} = mkf("labyrinth","Labyrinth chaos","A.6.4","conservative_flow", ...
    @(t,v) [sin(v(2)); sin(v(3)); sin(v(1))], [0.1;0;0], 0.1402, "numerical", 0.05);
S{end+1} = mkf("henon_heiles","Henon-Heiles system","A.6.5","conservative_flow", ...
    @(t,v) [v(3); v(4); -v(1)-2*v(1)*v(2); -v(2)-v(1)^2+v(2)^2], ...
    [0.499;0;0;0.03160676], 0.0450, "numerical", 0.02);

c = [S{:}];

if nargin >= 1
    hit = strcmp([c.name], name);
    if ~any(hit)
        error('nonantest:sprott_catalog:unknown', ...
              'no system named "%s" in the catalogue', name);
    end
    c = c(hit);
end
end

% ---------------------------------------------------------------- builders

function s = mk(name, pretty, section, category, f, x0, lambda, tier)
s = struct('name', string(name), 'pretty', string(pretty), ...
    'section', string(section), 'category', string(category), ...
    'kind', "map", 'f', f, 'x0', x0(:), 'lambda', lambda, ...
    'tier', string(tier), 'obs', 1, 'dt', NaN, 'usable', true, 'note', "");
end

function s = mkf(name, pretty, section, category, f, x0, lambda, tier, dt)
s = struct('name', string(name), 'pretty', string(pretty), ...
    'section', string(section), 'category', string(category), ...
    'kind', "flow", 'f', f, 'x0', x0(:), 'lambda', lambda, ...
    'tier', string(tier), 'obs', 1, 'dt', dt, 'usable', true, 'note', "");
end

% ------------------------------------------------- systems needing helpers

function w = dissStd(v)
y = mod(0.1*v(2) + 8.8*sin(v(1)), 2*pi);
w = [mod(v(1) + y, 2*pi); y];
end

function w = ikeda(v)
phi = 0.4 - 6/(1 + v(1)^2 + v(2)^2);
w = [1 + 0.9*(v(1)*cos(phi) - v(2)*sin(phi)); 0.9*(v(1)*sin(phi) + v(2)*cos(phi))];
end

function w = chirikov(v)
y = mod(v(2) + 1*sin(v(1)), 2*pi);
w = [mod(v(1) + y, 2*pi); y];
end

function w = henonArea(v)
ca = 0.24; sa = sqrt(1 - ca^2);
w = [v(1)*ca - (v(2) - v(1)^2)*sa; v(1)*sa + (v(2) - v(1)^2)*ca];
end

function w = chaoticWeb(v)
al = pi/2;
w = [v(1)*cos(al) - (v(2) + 1*sin(v(1)))*sin(al); ...
     v(1)*sin(al) + (v(2) + 1*sin(v(1)))*cos(al)];
end

function d = chua(v)
% dx/dt = alpha[y - x + b*x + 0.5*(a-b)*(|x+1| - |x-1|)]
% The bracketed terms are ADDED, per the appendix. Subtracting them instead
% (treating b*x + ... as a nonlinearity to remove) drives the system to a
% fixed point: std of x falls to 7e-24 over 500 samples.
al = 9; be = 100/7; a = 8/7; b = 5/7;
h = b*v(1) + 0.5*(a - b)*(abs(v(1)+1) - abs(v(1)-1));
d = [al*(v(2) - v(1) + h); v(1) - v(2) + v(3); -be*v(2)];
end
