NONAN Library: Surr_Theiler Namespace Reference
Surr_Theiler Namespace Reference
Functions
def Surr_Theiler20200723 (y, algorithm)
def surr1 (x, algorithm)
Function Documentation
surr1()
def Surr_Theiler.surr1 (x, algorithm)
z = surr1(x,algorithm)
Inputs: x, The input to be surrogated.
        algorithm, The selected algorithm to use.
Output: z, The surrogated time series.
References surr1().
Referenced by surr1(), and Surr_Theiler20200723().
Surr_Theiler20200723()
def Surr_Theiler.Surr_Theiler20200723 (y, algorithm)
z=Surr_Theiler20200723(y,algorithm)
inputs  - y, time series to be surrogated
             algorithm - the type of algorithm to be completed
outputs - z, surrogated time series
Remarks
- This code creates a surrogate time series according to Algorithm 0,
  Algorithm 1 or Algorithm 2.
Future Work
- None.
References
- Theiler, J., Eubank, S., Longtin, A., Galdrikian, B., & Doyne
  Farmer, J. (1992). Testing for nonlinearity in time series: the
  method of surrogate data. Physica D: Nonlinear Phenomena, 58(1–4),
  77–94. https://doi.org/10.1016/0167-2789(92)90102-S
Jun 2015 - Modified by Ben Senderling
         - Added function help section and plot commands for user
           feedback
         - The code was originally created as two algorithms. It was
           modified so one code included both functions.
Jul 2020 - Modified by Ben Senderling, bmchnonan@unomaha.edu
         - Changed file and function name.
         - Added reference.
References surr1(), and Surr_Theiler20200723().
Referenced by Surr_Theiler20200723().