NONAN Library: LyE_W Namespace Reference
LyE_W Namespace Reference
Functions
def LyE_W (x, Fs, tau, dim, evolve)
def get_next_point (flag, Y, current_point, current_point_pair, NPT, evolve, SCALEMX, ZMULT, ANGLMX)
def find_next_point (flag, theta, Ydisti, SCALEMX, ZMULT, ANGLMX)
Function Documentation
find_next_point()
def LyE_W.find_next_point (flag, theta, Ydisti, SCALEMX, ZMULT, ANGLMX)
Referenced by get_next_point().
get_next_point()
def LyE_W.get_next_point (flag, Y, current_point, current_point_pair, NPT, evolve, SCALEMX, ZMULT, ANGLMX)
References find_next_point().
Referenced by LyE_W().
LyE_W()
def LyE_W.LyE_W (x, Fs, tau, dim, evolve)
inputs  - x, time series
        - Fs, sampling frequency
        - tau, time lag
        - dim, embedding dimension
        - evolve, parameter of the same name from Wolf's 1985 paper. This
          code expects a number of frames as an input.
outputs - out, matrix detailing variables at each iteration
        - LyE, largest lyapunov exponent
[out,LyE] = LyE_W20200820(X,Fs,tau,dim,evolve,SCALEMX,SCALEMN,ANGLMX,ZMULT)
        - SCALEMX, length of which the local structure of the attractor
          is no longer being probed
        - SCALEMN, length below which noise predominates the attractors
          behavior
        - ANGLMX, maximum angle used to constrain replacements
        - ZMULT, multiplier used to increase SCALEMX, unused in the
          current version of the code
Remarks
- This code calculates the largest lyapunov exponent of a time series
  according to the algorithm detailed in Wolf's 1985 paper. This code has
  been aligned with his code published on the Matlab file exchange in
  2016. It will largely find the same replacement points, the remaining
  difference being in the replacement algorithm.
- The varargin can be used to specify some of the secondary parameters in
  the algorithm. All of the extra arguements must be specified if any are
  to be specified at all. Otherwise defaults are used.
- ZMULT is not currently used in the code but was in a previous version.
  Its place in the subroutine inputs and outputs was kept in case it is
  put back in.
- It should be noted that the process in the searching algorithm has a
  significant impact on the resulting LyE.
- The code expects evolve to be the number of frames to use but we
  encourage you to report this as a time-value in publications.
Prior - Created by Shane Wurdeman, unonbcf@unomaha.edu
      - Adapted by Brian Knarr, unonbcf@unomaha.edu
      - The code previously was influenced heavily by the FORTRAN syntax
        published in Wolf's 1985 paper. These were modified to better
        take advantage of MATLAB and speed up the code.
Mar 2017 - Modified by Ben Senderling, unonbcf@unomaha.edu
         - Changed parameter "n" to "evolve."
         - Changed "ZMULT" back to 1.
         - Aligned the code with Wolf's Matlab File Exchange submission
           to find the same replacement points. This is now essential his
           algorithm but retains the speed of previous versions.
Apr 2019 - Modified by Ben Senderling, unonbcf@unomaha.edu
         - Changed line 'range_exclude = range_exclude(range_exclude>=1 &
           range_exclude<=NPT);' to say '>=1' instead of '>1' to prevent
           self matches with the first point. This was indirectly
           accounted for by setting distances less than SCALEMN to 0.
         - '<SCALEMN' was removed from the code entirely and replaced with a
           '<=0'. This was checked against joint angles and EMG data. The
           change did not result in different pairs. This also removes an
          input.
References get_next_point().