NONAN Library: emd Namespace Reference
emd Namespace Reference
Functions
def emd (x, t=0, stop=np.array([0.05, 0.5, 0.05]), ndirs=4, display_sifting=0, MODE_COMPLEX=2, MAXITERATIONS=2000, FIXE=0, FIXE_H=0, MAXMODES=0, INTERP='cubic', mask=0, nargout=1)
None display_emd_fixe (t, m, mp, r, envminp, envmaxp, envmoyp, nbit, k, display_sifting)
def display_emd (t, m, mp, r, envminp, envmaxp, envmoyp, s, sb, sxp, sdt, sd2t, nbit, k, display_sifting, stop_sift)
def extr (np.ndarray x, int nargout=2)
def boundary_conditions (np.ndarray indmin, np.ndarray indmax, np.ndarray t, np.ndarray x, np.ndarray z, int nbsym)
def stop_EMD (np.ndarray r, int MODE_COMPLEX, int ndirs)
def mean_and_amplitude (np.ndarray m, np.ndarray t, str INTERP, int MODE_COMPLEX, int ndirs, int nargout=4)
def stop_sifting (np.ndarray m, np.ndarray t, float sd, float sd2, float tol, str INTERP, int MODE_COMPLEX, int ndirs, int nargout=2)
def stop_sifting_fixe (np.ndarray t, np.ndarray m, str INTERP, int MODE_COMPLEX, int ndirs)
def stop_sifting_fixe_h (np.ndarray t, np.ndarray m, str INTERP, int stop_count, int FIXE_H, int MODE_COMPLEX, int ndirs, int nargout=2)
def io (np.ndarray x, np.ndarray imf)
def init (x, t, stop, ndirs, display_sifting, MODE_COMPLEX, MAXITERATIONS, FIXE, FIXE_H, MAXMODES, INTERP, mask)
Function Documentation
boundary_conditions()
def emd.boundary_conditions (np.ndarray indmin, np.ndarray indmax, np.ndarray t, np.ndarray x, np.ndarray z, int nbsym)
Referenced by emd(), and mean_and_amplitude().
display_emd()
def emd.display_emd (t, m, mp, r, envminp, envmaxp, envmoyp, s, sb, sxp, sdt, sd2t, nbit, k, display_sifting, stop_sift)
Referenced by emd().
display_emd_fixe()
None emd.display_emd_fixe (t, m, mp, r, envminp, envmaxp, envmoyp, nbit, k, display_sifting)
Referenced by emd().
emd()
def emd.emd (x, t = 0, stop = np.array([0.05,0.5,0.05]), ndirs = 4, display_sifting = 0, MODE_COMPLEX = 2, MAXITERATIONS = 2000, FIXE = 0, FIXE_H = 0, MAXMODES = 0, INTERP = 'cubic', mask = 0, nargout = 1)
EMD  computes Empirical Mode Decomposition
Syntax
IMF = EMD(X)
IMF = EMD(X,...,'Option_name',Option_value,...)
IMF = EMD(X,OPTS)
[IMF,ORT,NB_ITERATIONS] = EMD(...)
Description
IMF = EMD(X) where X is a real vector computes the Empirical Mode
Decomposition [1] of X, resulting in a matrix IMF containing 1 IMF per row, the
last one being the residue. The default stopping criterion is the one proposed
in [2]:
at each point, mean_amplitude < THRESHOLD2*envelope_amplitude
&
mean of boolean array {(mean_amplitude)/(envelope_amplitude) > THRESHOLD} < TOLERANCE
&
|#zeros-#extrema|<=1
where mean_amplitude = abs(envelope_max+envelope_min)/2
and envelope_amplitude = abs(envelope_max-envelope_min)/2
IMF = EMD(X) where X is a complex vector computes Bivariate Empirical Mode
Decomposition [3] of X, resulting in a matrix IMF containing 1 IMF per row, the
last one being the residue. The default stopping criterion is similar to the
one proposed in [2]:
at each point, mean_amplitude < THRESHOLD2*envelope_amplitude
&
mean of boolean array {(mean_amplitude)/(envelope_amplitude) > THRESHOLD} < TOLERANCE
where mean_amplitude and envelope_amplitude have definitions similar to the
real case
IMF = EMD(X,...,'Option_name',Option_value,...) sets options Option_name to
the specified Option_value (see Options)
IMF = EMD(X,OPTS) is equivalent to the above syntax provided OPTS is a struct
object with field names corresponding to option names and field values being the
associated values
[IMF,ORT,NB_ITERATIONS] = EMD(...) returns an index of orthogonality
                    ________
        _  |IMF(i,:).*IMF(j,:)|
ORT = \ _____________________
        /
        ¯        || X ||²
    i~=j
and the number of iterations to extract each mode in NB_ITERATIONS
Options
stopping criterion options:
STOP: vector of stopping parameters [THRESHOLD,THRESHOLD2,TOLERANCE]
if the input vector's length is less than 3, only the first parameters are
set, the remaining ones taking default values.
default: [0.05,0.5,0.05]
FIX (int): disable the default stopping criterion and do exactly <FIX>
number of sifting iterations for each mode
FIX_H (int): disable the default stopping criterion and do <FIX_H> sifting
iterations with |#zeros-#extrema|<=1 to stop [4]
bivariate/complex EMD options:
COMPLEX_VERSION: selects the algorithm used for complex EMD ([3])
COMPLEX_VERSION = 1: "algorithm 1"
COMPLEX_VERSION = 2: "algorithm 2" (default)
NDIRS: number of directions in which envelopes are computed (default 4)
rem: the actual number of directions (according to [3]) is 2*NDIRS
other options:
T: sampling times (line vector) (default: 1:length(x))
MAXITERATIONS: maximum number of sifting iterations for the computation of each
mode (default: 2000)
MAXMODES: maximum number of imfs extracted (default: Inf)
DISPLAY: if equals to 1 shows sifting steps with pause
if equals to 2 shows sifting steps without pause (movie style)
rem: display is disabled when the input is complex
INTERP: interpolation scheme: 'linear', 'cubic', or 'spline' (default)
Important to note, 'spline' defaults to using quadratic spline interpolation. For 'cubic' spline interpolation use 'cubic'.
see numpy.interp1d documentation for details
MASK: masking signal used to improve the decomposition according to [5]
References
[1] N. E. Huang et al., "The empirical mode decomposition and the
Hilbert spectrum for non-linear and non stationary time series analysis",
Proc. Royal Soc. London A, Vol. 454, pp. 903-995, 1998
[2] G. Rilling, P. Flandrin and P. Gonçalves
"On Empirical Mode Decomposition and its algorithms",
IEEE-EURASIP Workshop on Nonlinear Signal and Image Processing
NSIP-03, Grado (I), June 2003
[3] G. Rilling, P. Flandrin, P. Gonçalves and J. M. Lilly.,
"Bivariate Empirical Mode Decomposition",
Signal Processing Letters (submitted)
[4] N. E. Huang et al., "A confidence limit for the Empirical Mode
Decomposition and Hilbert spectral analysis",
Proc. Royal Soc. London A, Vol. 459, pp. 2317-2345, 2003
[5] R. Deering and J. F. Kaiser, "The use of a masking signal to improve
empirical mode decomposition", ICASSP 2005
G. Rilling, last modification: 3.2007
gabriel.rilling@ens-lyon.fr
References boundary_conditions(), display_emd(), display_emd_fixe(), extr(), init(), io(), stop_EMD(), stop_sifting(), stop_sifting_fixe(), and stop_sifting_fixe_h().
extr()
def emd.extr (np.ndarray x, int nargout = 2)
Referenced by emd(), mean_and_amplitude(), and stop_EMD().
init()
def emd.init (x, t, stop, ndirs, display_sifting, MODE_COMPLEX, MAXITERATIONS, FIXE, FIXE_H, MAXMODES, INTERP, mask)
Referenced by emd().
io()
def emd.io (np.ndarray x, np.ndarray imf)
 ort = io(x,imf) computes the index of orthogonality
inputs : - x    : analyzed signal
         - imf  : empirical mode decomposition
References io().
Referenced by emd(), and io().
mean_and_amplitude()
def emd.mean_and_amplitude (np.ndarray m, np.ndarray t, str INTERP, int MODE_COMPLEX, int ndirs, int nargout = 4)
References boundary_conditions(), and extr().
Referenced by stop_sifting(), stop_sifting_fixe(), and stop_sifting_fixe_h().
stop_EMD()
def emd.stop_EMD (np.ndarray r, int MODE_COMPLEX, int ndirs)
References extr().
Referenced by emd().
stop_sifting()
def emd.stop_sifting (np.ndarray m, np.ndarray t, float sd, float sd2, float tol, str INTERP, int MODE_COMPLEX, int ndirs, int nargout = 2)
References mean_and_amplitude().
Referenced by emd().
stop_sifting_fixe()
def emd.stop_sifting_fixe (np.ndarray t, np.ndarray m, str INTERP, int MODE_COMPLEX, int ndirs)
References mean_and_amplitude().
Referenced by emd().
stop_sifting_fixe_h()
def emd.stop_sifting_fixe_h (np.ndarray t, np.ndarray m, str INTERP, int stop_count, int FIXE_H, int MODE_COMPLEX, int ndirs, int nargout = 2)
References mean_and_amplitude().
Referenced by emd().