NONAN Library: RQA Namespace Reference
RQA Namespace Reference
Functions
def RQA (DATA, TYPE, EMB, DEL, ZSCORE, NORM, LINELENGTH, SETPARA, SETVALUE, PLOTOPTION, nargout)
def setRadius (a, TYPE, radius, SETVALUE, radiusEnd, LINELENGTH)
def rqaPerRec (a, TYPE, radius, LINELENGTH)
def rqaHistograms (a, DATA, TYPE, radius)
def RQA_WeightedEntropy (WRP)
def label_components (bimg)
Function Documentation
label_components()
def RQA.label_components (bimg)
Input:  - bimg: The binary column to process
Output: - L: The labeled array.
Remarks:
    This subfunction serves to model the bwlabel function that exists in the MATLAB image processing library.
    Link: https://www.mathworks.com/help/images/ref/bwlabel.html
    The only exception is that this subfunction only handles one dimensional input, we are only expecting
    similar input from what you see in the RQA subfunction rqaHistograms. Our input consists of a NumPy
    array that may look something like: [0 1 1 1 0 0 0 1 1 0 1], our output would look something like
    [0 1 1 1 0 0 0 2 2 0 3], which gives each 'component' it's own label starting from 1 and incrementing
    for each time we encounter a 1 after encountering 0.
    The function in MATLAB takes in a secondary function which outlines connectivity, due to the input being
    one dimensional, we're ignoring that.
Referenced by rqaHistograms().
RQA()
def RQA.RQA (DATA, TYPE, EMB, DEL, ZSCORE, NORM, LINELENGTH, SETPARA, SETVALUE, PLOTOPTION, nargout)
Usage: (RP, RESULTS)=RQA20210210(DATA,TYPE,EMB,DEL,ZSCORE,NORM,LINELENGTH,SETPARA,SETVALUE,PLOTOPTION)
Inputs  - DATA, a double-variable with each dimension of the
                to-be-analyzed signal as a row of numbers in a separate
                column. If too many columns are present for the TYPE of
                analysis selected, the other columns will be ignored
                (i.e. for 'cRQA' only the first two columns will be
                used).
        - TYPE, a string indicating which type of RQA to run (i.e.
                'RQA', 'cRQA', 'jRQA', 'mdRQA'). The default value is
                TYPE = 'RQA'.
        - EMB, the number of embedding dimensions (i.e., EMB = 1 would
               be no embedding via time-delayed surrogates, just using
               the provided number of colums as dimensions. The default
               value is EMB = 1.
        - DEL, the delay parameter used for time-delayed embedding (if
               EMB > 1). The default value is DEL = 1.
        - ZSCORE, indicates, whether the data (i.e., the different
               columns of DATA, being the different signals or
               dimensions of a signal) should be z-scored before
               performing MdRQA:
               0 - no z-scoring of DATA
               1 - z-score columns of DATA
               The default value is ZSCORE = 0.
        - NORM, the type of norm by with the phase-space is normalized.
               The following norms are available:
               'euc' - Euclidean distance norm
               'max' - Maximum distance norm
               'min' - Minimum distance norm
               'non' - no normalization of phase-space
               The default value is NORM = 'non'.
        - SETPARA, the parameter which you would like to set a target
               value for the recurrence plot (i.e. 'radius' or
               'recurrence'). The default value is SETPARA = 'radius'.
        - SETVALUE, sets the value of the selected parameter. If
               SETVALUE = 1, then the radius will be set to 1 if SETPARA
               = 'radius' or the radius will be adjusted until the
               recurrence is equal to 1 if SETPARA = 'recurrence'. The
               default value if SETPARA = 'radius' is 1. The default
               value if SETPARA = 'recurrence' is 2.5.
        - PLOTOPTION, a 1 will display a plot, 0 will not display it.
        - nargout, a number of arguments we want to return from this function.
Outputs - RP is a matrix holding the resulting recurrence plot.
        - RESULTS is a dictionary holding the following recurrence
          variables:
          1.  DIM    - dimension of the input data (used for mdRQA)
          2.  EMB    - embedding dimension used in the calculation of the
                       distance matrix
          3.  DEL    - time lag used in the calculation of the distance
                       matrix
          4.  RADIUS - radius used for the recurrence plot
          5.  NORM   - type of normilization used for the distance matrix
          6.  ZSCORE - whether or not zscore was used
          7.  Size   - size of the recurrence plot
          8.  %REC   - percentage of recurrent points
          9.  %DET   - percentage of diagonally adjacent recurrent points
          10. MeanL  - average length of adjacent recurrent points
          11. MaxL   - maximum length of diagonally adjacent recurrent
                       points
          12. EntrL  - Shannon entropy of distribution of diagonal lines
          13. %LAM   - percentage of vertically adjacent recurrent points
          14. MeanV  - average length of diagonally adjacent recurrent
                       points
          15. MaxV   - maximum length of vertically adjacent recurrent
                       points
          16. EntrV  - Shannon entropy of distribution of vertical lines
          17. EntrW  - Weighted entropy of distribution of vertical
                       weighted sums
Remarks
- Computes a recurrence plot for either recurrence quantification
  analysis (RQA), cross recurrence quantification analysis (cRQA), joint
  recurrence quantification analysis (jRQA), or multidimensional
  recurrence quantification analysis (mdRQA). Either radius or target
  recurrence can be set.
Reference:
- Wallot, S., Roepstorff, A., & Monster, D. (2016). Multidimensional
  Recurrence Quantification Analysis (MdRQA) for the analysis of
  multidimensional time-series: A software implementation in MATLAB and
  its application to group-level data in joint action. Frontiers in
  Psychology, 7, 1835. http://dx.doi.org/10.3389/fpsyg.2016.01835
- Eroglu, D., Peron, T. K. D., Marwan, N., Rodrigues, F. A., Costa, L. D.
  F., Sebek, M., ... & Kurths, J. (2014). Entropy of weighted recurrence
  plots. Physical Review E, 90(4), 042919.
Jul 2016 Modified by Sebastian Wallot
         - VERSION 1.0.0
           28. July 2016 by Sebastian Wallot, Max Planck Insitute for
           Empirical Aesthetics, Frankfurt, Germany & Dan M?nster, Aarhus
           University, Aarhus, Denmark
Jul 2017 Modified by Will Denton
         - VERSION 1.1.0
           06. July 2017 by Will Denton (wdenton@unomaha.edu), Troy Rand
           (troyrand@gmail.com), and Casey Wiens (cwiens32@gmail.com),
           Biomechanics Research Building, University of Nebraska at
           Omaha. Changes include cleaning up some errors, making the
           default input arguments function correctly, incorperating
           other types of RQA (e.g. RQA, CRQA, JRQA), allowing %REC to be
           set instead of radius, incorporating weighted recurrence
           plots, and adding weighted entropy.
May 2019 Modified by Will Denton
         - VERSION 1.1.1 (05/09/2019)
         - Added updates/patching.
         - Added usage tracking to allow the Department of Biomechanics
           at the University of Omaha see which codes and versions are
           being used.
         - Added error reporting to allow the Department of Biomechanics
           at the University of Omaha to make improvements to this code.
Nov 2019 Modified by Will Denton
         - VERSION 1.1.2 (11/18/2019)
         - Fixed usage and error reporting to work with MacOS.
         - Fixed left plot to align with the recurrence plot when zoomed
           in and panning around.
Jul 2020 Modified by Ben Senderling, bmchnonan@unomaha.edu
         - Removed automatic update code and version history code.
Dec 2020 Modified by Ben Senderling, bmchnonan@unomaha.edu
         - Commented out waitbar and added PLOTOPTION input to control
           figure creation.
Feb 2021 Modified by Ben Senderling, bmchnonan@unomaha.edu
         - Made line length an input with a default of 1.
Copyright 2020 Nonlinear Analysis Core, Center for Human Movement
Variability, University of Nebraska at Omaha
Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are
met:
1. Redistributions of source code must retain the above copyright notice,
   this list of conditions and the following disclaimer.
2. Redistributions in binary form must reproduce the above copyright
   notice, this list of conditions and the following disclaimer in the
   documentation and/or other materials provided with the distribution.
3. Neither the name of the copyright holder nor the names of its
   contributors may be used to endorse or promote products derived from
   this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
References RQA_WeightedEntropy(), rqaHistograms(), rqaPerRec(), and setRadius().
RQA_WeightedEntropy()
def RQA.RQA_WeightedEntropy (WRP)
Usage: Swrp = RQA_WeightedEntropy(WRP)
Input:  WRP,
Output: Swrp,
References RQA_WeightedEntropy().
Referenced by RQA(), and RQA_WeightedEntropy().
rqaHistograms()
def RQA.rqaHistograms (a, DATA, TYPE, radius)
Usage: (diag_hist, vertical_hist) = rqaHistograms(A, DATA, TYPE, radius)
Input:  - a, stores the recurrence matrix.
        - DATA,
        - TYPE,
        - radius
Output: - diag_hist,
        - vertical_hist,
References label_components(), and rqaHistograms().
Referenced by RQA(), and rqaHistograms().
rqaPerRec()
def RQA.rqaPerRec (a, TYPE, radius, LINELENGTH)
Usage: perRec = rqaPerRec(A, TYPE, radius, LINELENGTH)
Input:  - a, pairwise euclidean distance values from our DATA matrix.
        - TYPE, a string indicating which type of RQA to run (i.e.
           'RQA', 'cRQA', 'jRQA', 'mdRQA'). The default value is
           TYPE = 'RQA'.
        - radius,
        - LINELENGTH
Output: - perRec
References rqaPerRec().
Referenced by RQA(), rqaPerRec(), and setRadius().
setRadius()
def RQA.setRadius (a, TYPE, radius, SETVALUE, radiusEnd, LINELENGTH)
Usage: (perRec, radiusFinal) = setRadius(a, TYPE, radius, SETVALUE, radiusEnd, LINELENGTH)
Input:  - a, pairwise euclidean distance values of our DATA matrix.
        - TYPE, a string indicating which type of RQA to run (i.e.
            'RQA', 'cRQA', 'jRQA', 'mdRQA'). The default value is
            TYPE = 'RQA'.
        - radius,
        - SETVALUE,sets the value of the selected parameter. If
            SETVALUE = 1, then the radius will be set to 1 if SETPARA
            = 'radius' or the radius will be adjusted until the
            recurrence is equal to 1 if SETPARA = 'recurrence'. The
            default value if SETPARA = 'radius' is 1. The default
            value if SETPARA = 'recurrence' is 2.5.
        - radiusEnd,
        - LINELENGTH,
Output: - perRec,
        - radiusFinal,
References rqaPerRec(), and setRadius().
Referenced by RQA(), and setRadius().