NONAN Library: Ent_MS_Plus Namespace Reference
Ent_MS_Plus Namespace Reference
Functions
def Ent_MS_Plus (x, tau, m, r)
def Samp_Ent (data, m, r)
def Fuzzy_Ent (series, dim, r, n)
Function Documentation
Ent_MS_Plus()
def Ent_MS_Plus.Ent_MS_Plus (x, tau, m, r)
(RCMSE, CMSE, MSE, MSFE) = RCMS_Ent(x, tau, m, r)
inputs - x, single column time seres
       - tau, greatest scale factor
       - m, length of vectors to be compared
       - R, radius for accepting matches (as a proportion of the
            standard deviation)
output - RCMSE, Refined Composite Multiscale Entropy
       - CMSE, Composite Multiscale Entropy
       - MSE, Multiscale Entropy
       - MSFE, Multiscale Fuzzy Entropy
       - GMSE, Generalized Multiscale Entropy
Remarks
- This code finds the Refined Composite Multiscale Sample Entropy,
  Composite Multiscale Entropy, Multiscale Entropy, Multiscale Fuzzy
  Entropy and Generalized Multiscale Entropy of a data series using the
  methods described by - Wu, Shuen-De, et al. 2014. "Analysis of complex
  time series using refined composite multiscale entropy." Physics
  Letters A. 378, 1369-1374.
- Each of these methods calculates entropy at different scales. These
  scales range from 1 to tau in increments of 1.
- The Complexity Index (CI) is not calculated by this code. Because the scales
  are incremented by 1 the C is the summation of all the elements in each
  array. For example the CI of MSE would be sum(MSE).
20170828 Created by Will Denton, bmchnonan@unomaha.edu
20201001 Modified by Ben Senderling, bmchnonan@unomaha.edu
         - Modifed to calculate all scales in this single code instead of
           needing to be in an external for loop.
References Fuzzy_Ent(), and Samp_Ent().
Fuzzy_Ent()
def Ent_MS_Plus.Fuzzy_Ent (series, dim, r, n)
Function which computes the Fuzzy Entropy (FuzzyEn) of a time series. The
algorithm presented by Chen et al. at "Charactirization of surface EMG
signal based on fuzzy entropy" (DOI: 10.1109/TNSRE.2007.897025) has been
followed.
INPUT:
        series: the time series.
        dim: the embedding dimesion employed in the SampEn algorithm.
        r: the width of the fuzzy exponential function.
        n: the step of the fuzzy exponential function.
OUTPUT:
        FuzzyEn: the FuzzyEn value.
PROJECT: Research Master in signal theory and bioengineering - University of Valladolid
DATE: 11/10/2014
VERSION: 1
AUTHOR: Jess Monge lvarez
Referenced by Ent_MS_Plus().
Samp_Ent()
def Ent_MS_Plus.Samp_Ent (data, m, r)
[SE,sum_nm,sum_nm1] = Samp_Ent(data,m,r)
This is a faster version of the previous code - Samp_En.m
inputs     - data, single column time seres
           - m, length of vectors to be compared
           - R, radius for accepting matches (as a proportion of the
                standard deviation)
output     - SE, sample entropy
           - sum_nm, total number of matches for vector length m
           - sum_nm1, total number of matches for vector length m+1
Remarks
This code finds the sample entropy of a data series using the method
described by - Richman, J.S., Moorman, J.R., 2000. "Physiological
time-series analysis using approximate entropy and sample entropy."
Am. J. Physiol. Heart Circ. Physiol. 278, H2039–H2049.
J McCamley May, 2016
W Denton August, 2017 (Made count total number of matches for each vector length, necessary for CMSE and RCMSE)
References Samp_Ent().
Referenced by Ent_MS_Plus(), and Samp_Ent().