NONAN Library: AMI_Thomas Namespace Reference
AMI_Thomas Namespace Reference
Functions
Union[np.ndarray, float] AMI_Thomas (np.ndarray x, Union[int, np.ndarray, list] L)
float average_mutual_information (np.ndarray data)
np.ndarray univariate_kernel_density (np.ndarray value, np.ndarray data, float window)
np.ndarray bivariate_kernel_density (np.ndarray value, np.ndarray data, float Hone, float Htwo)
def bivariate_kernel_density_sub (n, prob, number_pts)
np.ndarray linear_depth (np.ndarray feet, np.ndarray toes)
np.ndarray extended (np.ndarray vector, int n, bool vertical)
Function Documentation
AMI_Thomas()
Union[np.ndarray,float] AMI_Thomas.AMI_Thomas (np.ndarray x, Union[int,np.ndarray,list] L)
Usage: (tau,ami)=AMI_Thomas(x,L)
inputs:    x - time series, vertically orientedtrc files selected by user
           L - Maximum lag to calculate AMI until
outputs:   tau - first true minimum of the AMI vs lag plot
           AMI - a vertically oriented vector containing values of AMI
           from a lag of 0 up the input L
[ami]=AMI_Thomas(x,y)
inputs:   - x, single column array with the same length as y
          - y, single column array with the same length as x
outputs   - ami, the average mutual information between the two arrays
Remarks
- This code uses a published method of calculating AMI to find an
  acceptable lag with which to perform phase space reconstruction.
- The algorithm is publically available at the citation below. Make sure
  to cite this work. The subroutine is fully their work.
- In the case a value of tau could not be found before L the code will
  return an empty tau and the ami vector.
- If it does find multiple values of tau but no definative minimum it
  will return all of these values.
Future Work
- None.
References
- Thomas, R. D., Moses, N. C., Semple, E. A., & Strang, A. J. (2014). An
  efficient algorithm for the computation of average mutual information:
  Validation and implementation in Matlab. Journal of Mathematical
  Psychology, 61(September 2015), 45–59.
  https://doi.org/10.1016/j.jmp.2014.09.001
Sep 2015 - Adapted by Ben Senderling, email: bensenderling@gmail.com
                 Below I've set the code published by Thomas, Semple and
                 Strang to calculate AMI at various lags and to suggest
                 an appropriate tau.
Apr 2021 - Modified by Ben Senderling, email bmchnonan@unomaha.edu
         - Modified in conjunction with NONAN validation efforts.
           Added the variable input arguements and second implementation.
Validation
Damped oscillator (approximate tau ~ 33)
L=35
t=(1:500)'
a=0.005
w=0.05
x=exp(-a*t).*sin(w*t)
Copyright 2020 Nonlinear Analysis Core, Center for Human Movement
Variability, University of Nebraska at Omaha
Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are
met:
1. Redistributions of source code must retain the above copyright notice,
   this list of conditions and the following disclaimer.
2. Redistributions in binary form must reproduce the above copyright
   notice, this list of conditions and the following disclaimer in the
   documentation and/or other materials provided with the distribution.
3. Neither the name of the copyright holder nor the names of its
   contributors may be used to endorse or promote products derived from
   this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES LOSS OF USE, DATA, OR
PROFITS OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
References average_mutual_information().
average_mutual_information()
float AMI_Thomas.average_mutual_information (np.ndarray data)
Usage: AMI = average_mutual_information(data)
Calculates average mutual information between
two
columns of data. It uses kernel density
estimation,
with a globally adjusted Gaussian kernel.
Input should be an n-by-2 matrix, with data sets
in adjacent
column vectors.
Output is a scalar.
References average_mutual_information(), bivariate_kernel_density(), and univariate_kernel_density().
Referenced by AMI_Thomas(), and average_mutual_information().
bivariate_kernel_density()
np.ndarray AMI_Thomas.bivariate_kernel_density (np.ndarray value, np.ndarray data, float Hone, float Htwo)
Usage: y = bivariate_kernel_density(value, data, Hone, Htwo)
Calculates bivariate kernel density estimates
of probability.
Inputs are: - value (m x 2 matrix), where density is estimated
            - data (n x 2 matrix), the data used to estimate the density
            - Hone (scalar) and Htwo (scalar) to use for the widths of density estimation.
Output is an m-vector of probabilities estimated at the values in ’value’.
References bivariate_kernel_density(), bivariate_kernel_density_sub(), and linear_depth().
Referenced by average_mutual_information(), and bivariate_kernel_density().
bivariate_kernel_density_sub()
def AMI_Thomas.bivariate_kernel_density_sub (n, prob, number_pts)
Referenced by bivariate_kernel_density().
extended()
np.ndarray AMI_Thomas.extended (np.ndarray vector, int n, bool vertical)
Takes an m-dimensional row vector and outputs an
n-by-m matrix with n-many consecutive repeats of
the vector. Similarly,  it takes an
m-dimensional column vector and outputs an
m-by-n matrix.
Else, it returns the original input.
Referenced by univariate_kernel_density().
linear_depth()
np.ndarray AMI_Thomas.linear_depth (np.ndarray feet, np.ndarray toes)
linear_depth takes a matrix ‘feet’ and lengthens
it in blocks, takes a matrix ‘toes’ and lengthens
it in Extended repeats, and then adds the
lengthened ‘feet’ and ‘toes’ matrices to achieve
all sum combinations of their rows.
feet and toes have the same number of columns
Referenced by bivariate_kernel_density().
univariate_kernel_density()
np.ndarray AMI_Thomas.univariate_kernel_density (np.ndarray value, np.ndarray data, float window)
Usage:  y = univariate_kernel_density(value, data, window)
Estimates univariate density using kernel
density estimation.
Inputs are: - value (m-vector), where density is estimated
            - data (n-vector), the data used to estimate the density
            - window (scalar), used for the width of density estimation.
Output is an m-vector of probabilities.
References extended(), and univariate_kernel_density().
Referenced by average_mutual_information(), and univariate_kernel_density().