NONAN Library: FNN Namespace Reference
FNN Namespace Reference
Functions
def FNN (data, tau, MaxDim, Rtol, Atol, speed)
def kd_part (y_in, z_in, bin_size)
def kd_search (node, m_search, yq, pqd, y_model, z_model, L_done, pqr, pqz, b_upper, b_lower, sort_list, node_list)
def overlap (yq, m_search, pqd, b_upper, b_lower)
Function Documentation
FNN()
def FNN.FNN (data, tau, MaxDim, Rtol, Atol, speed)
  data - column oriented time series
  tau - time delay
  MaxDim - maximum embedding dimension
  Rtol - threshold for the first criterion
  Atol - threshold for teh second criterion
  speed - a 0 for the code to calculate to the MaxDim or a 1 for the code
          to finish once a minimum is found
Remarks
- This code determines the embedding dimension for a time series using
  the false nearest neighbors method.
- Recommended values are Rtol=15 and Atol=2;
- Reference:   "Determining embedding dimension for phase-space
                reconstruction using a geometrical construction",
                M. B. Kennel, R. Brown, and H.D.I. Abarbanel,
                Physical Review A, Vol 45, No 6, 15 March 1992,
                pp 3403-3411.
Future Work
- Currently there are two methods of detecting a minimal percentage of
  false nearest neighbors. One method checks for a minima or zero
  percentage, the other looks for a limit. Currently only dim is
  returned. This code can be modified to use a comprimise of the two.
Prior - Created by someone
Feb 2015 - Modified by Ben Senderling, email: unonbcf@unomaha.edu
           No changes were made to the algorithm. Checks were added to
           provide information to the user in case of an error. The two
           methods described in future work were also modified to work
           cooperatively. In a previous version the second method (dim)
           overwrote the first method (dim2).
Sep 2015 - Modified by Ben Senderling, email: unonbcf@unomaha.edu
           Previously, dim was found after the for loop, this version has
           been modified to allow the code to find the minimum as it
           calculates FNN. This is set within the inputs.
           The check that was previously put in has been commented out.
Oct 2015 - Modified by John McCamley, email: unonbcf@unomaha.edu
         - Embedded other required functions as subroutines.
Mar 2017 - Modified by Ben Senderling, email: unonbcf@unomaha.edu
         - Removed global variables in favor of passing the variables
           from function to function directly. This significantly
           improved performance. Checked that the calculated percentages
           of nearest neighbors are the same as the previous version.
May 2020 - Modified by Ben Senderling, bmchnonan@unomaha.edu
         - Added if statement checkeding data orientation.
Jul 2020 - Modified by Ben Senderling, bmchnonan@unomaha.edu
         - Changed indexing throughout so the input data array doesn't
           need to be reoriented. Changing this sped the code up an
           average 11% on 10 test signals.
         - Removed a couple small for loops and replaced with indexed
           operations. Was also able to remove within function and
           replaced with a single line of code.
         - Removed perviously commented out lines of code that were no
           longer used.
References kd_part(), and kd_search().
kd_part()
def FNN.kd_part (y_in, z_in, bin_size)
Create a kd-tree and partitioned database for
efficiently finding the nearest neighbors to a point
in a d-dimensional space.
y_in: original phase space data
z_in: original phase space data corresponding to y_in
bin_size: maximum number of distinct points for each bin
The outputs are placed into global variables used by
kdsearch and its subroutines.
The outputs are...
sort_list(:,1): discriminator: dimension to use in dividing data
sort_list(:,2): partition: boundary for dividing data
node_list(i,:): contains data for the i-th partition
node_list(:,1): 1st element in y of this partition
node_list(:,2): last element in y of this partition
node_list(:,3): location in node_list of left branch
node_list(:,4): location in node_list of right branch
y_model: phase space data partitioned into a binary tree
z_model: phase space data corresponding to each y_model point
Algorithms from:
"Data Structures for Range Searching", J.L. Bently, J.H. Friedman,
ACM Computing Surveys, Vol 11, No 4, p 397-409, December 1979
"An Algorithm for Finding Best Matches in Logarithmic Expected Time",
J.H. Friedman, J.L. Bentley, R.A. Finkel, ACM Transactions on
Mathematical Software, Vol 3, No 3, p 209-226, September 1977.
Mar 2015 - Modified by Ben Senderling, phone 267-980-0425, email bensenderling@gmail.com
              - Formatted.
Referenced by FNN().
kd_search()
def FNN.kd_search (node, m_search, yq, pqd, y_model, z_model, L_done, pqr, pqz, b_upper, b_lower, sort_list, node_list)
  [] = kdsearch(node)
  node - unknown
Remarks
- Search a kd_tree to find the nearest matches to the global variable
  yq, a vector.  The nearest matches will be put in the global variable
  pqr, and their distances in pqd.  See loclin_kd for a usage example.
- pqd: Starts as an 1x2 with [inf, inf], then it is added to with the values from dist.
  If pqd is longer than m_search, then only the values up to m_search are kept.
- pqr: Starts as an empty array, then the data from y_model is added with the bounds
  defined by yi which is also defined by node_list. Then the last two data points are
  kept just like with pqd.
- pqz: The same concept as pqr, except it is using data from the z_model.
- index: Records the indices that are to be traversed to create the sorted order for pqd.
  This is used later on for pqr & pqz to order those to arrays by the order defined by index.
Future Work
- This code could be commmented to be understood easier.
Feb 2015 - Modified by Ben Senderling, phone 267-980-0425, email bensenderling@gmail.com
         - Commented and formated
References kd_search(), and overlap().
Referenced by FNN(), and kd_search().
overlap()
def FNN.overlap (yq, m_search, pqd, b_upper, b_lower)
L = overlap
Inputs: yq, m_search, pqd, b_upper, b_lower.
Outputs: L - unknown
Remarks
- References: - "Data Structures for Range Searching", J.L. Bently, J.H.
                Friedman, ACM Computing Surveys, Vol 11, No 4, p 397-409,
                December 1979.
              - "An Algorithm for Finding Best Matches in Logarithmic
                Expected Time", J.H. Friedman, J.L. Bentley, R.A. Finkel,
                ACM Transactions on Mathematical Software, Vol 3, No 3,
                p 209-226, September 1977.
Future Work
- None.
Mar 2015 - Modified by Ben Senderling, phone 267-980-0425, email bensenderling@gmail.com
Referenced by kd_search().